/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * TechPro.Api
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { apiFetch } from '../fetcher';
export interface UsuarioResponse {
  id?: string;
  /** @nullable */
  nome?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  papel?: string | null;
  tenantId?: string;
}

export interface AuthResponse {
  /** @nullable */
  accessToken?: string | null;
  expiraEm?: string;
  usuario?: UsuarioResponse;
}

export interface EmpresaResponse {
  id?: string;
  /** @nullable */
  nome?: string | null;
}

export interface LoginRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  senha?: string | null;
}

export interface MeResponse {
  id?: string;
  /** @nullable */
  nome?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  papel?: string | null;
  tenantId?: string;
  empresa?: EmpresaResponse;
}

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  [key: string]: unknown;
}

export interface RegistrarRequest {
  /** @nullable */
  nomeEmpresa?: string | null;
  /** @nullable */
  nome?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  senha?: string | null;
}

/**
 * @nullable
 */
export type ValidationProblemDetailsErrors = {[key: string]: string[]} | null;

export interface ValidationProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  errors?: ValidationProblemDetailsErrors;
  [key: string]: unknown;
}

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type postApiAuthRegistrarResponse201 = {
  data: AuthResponse
  status: 201
}

export type postApiAuthRegistrarResponse400 = {
  data: ValidationProblemDetails
  status: 400
}

export type postApiAuthRegistrarResponse409 = {
  data: ProblemDetails
  status: 409
}

export type postApiAuthRegistrarResponseSuccess = (postApiAuthRegistrarResponse201) & {
  headers: Headers;
};
export type postApiAuthRegistrarResponseError = (postApiAuthRegistrarResponse400 | postApiAuthRegistrarResponse409) & {
  headers: Headers;
};

export type postApiAuthRegistrarResponse = (postApiAuthRegistrarResponseSuccess | postApiAuthRegistrarResponseError)

export const getPostApiAuthRegistrarUrl = () => {




  return `/api/auth/registrar`
}

export const postApiAuthRegistrar = async (registrarRequest?: RegistrarRequest, options?: RequestInit): Promise<postApiAuthRegistrarResponse> => {

  return apiFetch<postApiAuthRegistrarResponse>(getPostApiAuthRegistrarUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registrarRequest)
  }
);}





export const getPostApiAuthRegistrarMutationOptions = <TError = ValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegistrar>>, TError,{data?: RegistrarRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegistrar>>, TError,{data?: RegistrarRequest}, TContext> => {

const mutationKey = ['postApiAuthRegistrar'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRegistrar>>, {data?: RegistrarRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRegistrar(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRegistrarMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRegistrar>>>
    export type PostApiAuthRegistrarMutationBody = RegistrarRequest | undefined
    export type PostApiAuthRegistrarMutationError = ValidationProblemDetails | ProblemDetails

    export const usePostApiAuthRegistrar = <TError = ValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegistrar>>, TError,{data?: RegistrarRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRegistrar>>,
        TError,
        {data?: RegistrarRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthRegistrarMutationOptions(options), queryClient);
    }

export type postApiAuthLoginResponse200 = {
  data: AuthResponse
  status: 200
}

export type postApiAuthLoginResponse400 = {
  data: ValidationProblemDetails
  status: 400
}

export type postApiAuthLoginResponse401 = {
  data: ProblemDetails
  status: 401
}

export type postApiAuthLoginResponseSuccess = (postApiAuthLoginResponse200) & {
  headers: Headers;
};
export type postApiAuthLoginResponseError = (postApiAuthLoginResponse400 | postApiAuthLoginResponse401) & {
  headers: Headers;
};

export type postApiAuthLoginResponse = (postApiAuthLoginResponseSuccess | postApiAuthLoginResponseError)

export const getPostApiAuthLoginUrl = () => {




  return `/api/auth/login`
}

export const postApiAuthLogin = async (loginRequest?: LoginRequest, options?: RequestInit): Promise<postApiAuthLoginResponse> => {

  return apiFetch<postApiAuthLoginResponse>(getPostApiAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(loginRequest)
  }
);}





export const getPostApiAuthLoginMutationOptions = <TError = ValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data?: LoginRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data?: LoginRequest}, TContext> => {

const mutationKey = ['postApiAuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthLogin>>, {data?: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogin>>>
    export type PostApiAuthLoginMutationBody = LoginRequest | undefined
    export type PostApiAuthLoginMutationError = ValidationProblemDetails | ProblemDetails

    export const usePostApiAuthLogin = <TError = ValidationProblemDetails | ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data?: LoginRequest}, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthLogin>>,
        TError,
        {data?: LoginRequest},
        TContext
      > => {
      return useMutation(getPostApiAuthLoginMutationOptions(options), queryClient);
    }

export type postApiAuthRefreshResponse200 = {
  data: AuthResponse
  status: 200
}

export type postApiAuthRefreshResponse401 = {
  data: ProblemDetails
  status: 401
}

export type postApiAuthRefreshResponseSuccess = (postApiAuthRefreshResponse200) & {
  headers: Headers;
};
export type postApiAuthRefreshResponseError = (postApiAuthRefreshResponse401) & {
  headers: Headers;
};

export type postApiAuthRefreshResponse = (postApiAuthRefreshResponseSuccess | postApiAuthRefreshResponseError)

export const getPostApiAuthRefreshUrl = () => {




  return `/api/auth/refresh`
}

export const postApiAuthRefresh = async ( options?: RequestInit): Promise<postApiAuthRefreshResponse> => {

  return apiFetch<postApiAuthRefreshResponse>(getPostApiAuthRefreshUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostApiAuthRefreshMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,void, TContext> => {

const mutationKey = ['postApiAuthRefresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRefresh>>, void> = () => {


          return  postApiAuthRefresh(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRefresh>>>

    export type PostApiAuthRefreshMutationError = ProblemDetails

    export const usePostApiAuthRefresh = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRefresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiAuthRefreshMutationOptions(options), queryClient);
    }

export type postApiAuthLogoutResponse204 = {
  data: void
  status: 204
}

export type postApiAuthLogoutResponseSuccess = (postApiAuthLogoutResponse204) & {
  headers: Headers;
};
;

export type postApiAuthLogoutResponse = (postApiAuthLogoutResponseSuccess)

export const getPostApiAuthLogoutUrl = () => {




  return `/api/auth/logout`
}

export const postApiAuthLogout = async ( options?: RequestInit): Promise<postApiAuthLogoutResponse> => {

  return apiFetch<postApiAuthLogoutResponse>(getPostApiAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostApiAuthLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof apiFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogout>>, TError,void, TContext> => {

const mutationKey = ['postApiAuthLogout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthLogout>>, void> = () => {


          return  postApiAuthLogout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogout>>>

    export type PostApiAuthLogoutMutationError = unknown

    export const usePostApiAuthLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogout>>, TError,void, TContext>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiAuthLogoutMutationOptions(options), queryClient);
    }

export type getApiAuthMeResponse200 = {
  data: MeResponse
  status: 200
}

export type getApiAuthMeResponse401 = {
  data: ProblemDetails
  status: 401
}

export type getApiAuthMeResponse404 = {
  data: ProblemDetails
  status: 404
}

export type getApiAuthMeResponseSuccess = (getApiAuthMeResponse200) & {
  headers: Headers;
};
export type getApiAuthMeResponseError = (getApiAuthMeResponse401 | getApiAuthMeResponse404) & {
  headers: Headers;
};

export type getApiAuthMeResponse = (getApiAuthMeResponseSuccess | getApiAuthMeResponseError)

export const getGetApiAuthMeUrl = () => {




  return `/api/auth/me`
}

export const getApiAuthMe = async ( options?: RequestInit): Promise<getApiAuthMeResponse> => {

  return apiFetch<getApiAuthMeResponse>(getGetApiAuthMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAuthMeQueryKey = () => {
    return [
    `/api/auth/me`
    ] as const;
    }


export const getGetApiAuthMeQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = ProblemDetails>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthMe>>> = ({ signal }) => getApiAuthMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthMeQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthMe>>>
export type GetApiAuthMeQueryError = ProblemDetails


export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = ProblemDetails>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthMe>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAuthMe<TData = Awaited<ReturnType<typeof getApiAuthMe>>, TError = ProblemDetails>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthMe>>, TError, TData>>, request?: SecondParameter<typeof apiFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
