// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechPro.Api.Shared.Persistence;

#nullable disable

namespace TechPro.Api.Migrations
{
    [DbContext(typeof(TechProDbContext))]
    [Migration("20260721045032_Avaliacoes")]
    partial class Avaliacoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_papeis");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("papeis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b0c579-4f6e-4a56-9d10-2f6a1e01a001"),
                            ConcurrencyStamp = "seed-gestor",
                            Name = "gestor",
                            NormalizedName = "GESTOR"
                        },
                        new
                        {
                            Id = new Guid("a1b0c579-4f6e-4a56-9d10-2f6a1e01a002"),
                            ConcurrencyStamp = "seed-tecnico",
                            Name = "tecnico",
                            NormalizedName = "TECNICO"
                        },
                        new
                        {
                            Id = new Guid("a1b0c579-4f6e-4a56-9d10-2f6a1e01a003"),
                            ConcurrencyStamp = "seed-atendente",
                            Name = "atendente",
                            NormalizedName = "ATENDENTE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_papel_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_papel_claims_role_id");

                    b.ToTable("papel_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_usuario_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usuario_claims_user_id");

                    b.ToTable("usuario_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_usuario_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_usuario_logins_user_id");

                    b.ToTable("usuario_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_usuario_papeis");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_usuario_papeis_role_id");

                    b.ToTable("usuario_papeis", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_usuario_tokens");

                    b.ToTable("usuario_tokens", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.Agendamentos.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AparelhoMarca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aparelho_marca");

                    b.Property<string>("AparelhoModelo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("aparelho_modelo");

                    b.Property<DateTimeOffset?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_em");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("DescricaoProblema")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao_problema");

                    b.Property<string>("EmailContato")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email_contato");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fim");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("NomeContato")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_contato");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origem");

                    b.Property<DateTimeOffset?>("ReagendadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reagendado_em");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("servico_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("TelefoneContato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone_contato");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_agendamentos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_agendamentos_cliente_id");

                    b.HasIndex("ServicoId")
                        .HasDatabaseName("ix_agendamentos_servico_id");

                    b.HasIndex("TenantId", "Data")
                        .HasDatabaseName("ix_agendamentos_tenant_id_data");

                    b.ToTable("agendamentos", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.Agendamentos.BloqueioAgenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<TimeOnly>("HoraFim")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_fim");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_bloqueios_agenda");

                    b.HasIndex("TenantId", "Data")
                        .HasDatabaseName("ix_bloqueios_agenda_tenant_id_data");

                    b.ToTable("bloqueios_agenda", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.Agendamentos.EntradaFilaEspera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgendamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("agendamento_id");

                    b.Property<string>("AparelhoMarca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aparelho_marca");

                    b.Property<string>("AparelhoModelo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("aparelho_modelo");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataPreferida")
                        .HasColumnType("date")
                        .HasColumnName("data_preferida");

                    b.Property<string>("DescricaoProblema")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao_problema");

                    b.Property<string>("EmailContato")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email_contato");

                    b.Property<string>("MotivoDescarte")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_descarte");

                    b.Property<string>("NomeContato")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_contato");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origem");

                    b.Property<DateTimeOffset?>("ResolvidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolvida_em");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("servico_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TelefoneContato")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone_contato");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_fila_espera");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_fila_espera_cliente_id");

                    b.HasIndex("ServicoId")
                        .HasDatabaseName("ix_fila_espera_servico_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_fila_espera_tenant_id_status");

                    b.ToTable("fila_espera", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.Agendamentos.HorarioFuncionamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("Abertura")
                        .HasColumnType("time without time zone")
                        .HasColumnName("abertura");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer")
                        .HasColumnName("dia_semana");

                    b.Property<TimeOnly>("Fechamento")
                        .HasColumnType("time without time zone")
                        .HasColumnName("fechamento");

                    b.Property<TimeOnly?>("IntervaloFim")
                        .HasColumnType("time without time zone")
                        .HasColumnName("intervalo_fim");

                    b.Property<TimeOnly?>("IntervaloInicio")
                        .HasColumnType("time without time zone")
                        .HasColumnName("intervalo_inicio");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_horarios_funcionamento");

                    b.HasIndex("TenantId", "DiaSemana")
                        .IsUnique()
                        .HasDatabaseName("ix_horarios_funcionamento_tenant_id_dia_semana");

                    b.ToTable("horarios_funcionamento", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.Clientes.Aparelho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Imei")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("imei");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("modelo");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacoes");

                    b.Property<string>("SenhaDesbloqueio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("senha_desbloqueio");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_aparelhos");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_aparelhos_cliente_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_aparelhos_tenant_id");

                    b.ToTable("aparelhos", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.Clientes.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AnonimizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonimizado_em");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int?>("ClientePrincipalId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_principal_id");

                    b.Property<DateTimeOffset?>("ConsentimentoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consentimento_em");

                    b.Property<bool>("ConsentiuComunicacoes")
                        .HasColumnType("boolean")
                        .HasColumnName("consentiu_comunicacoes");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco");

                    b.Property<bool>("Exemplo")
                        .HasColumnType("boolean")
                        .HasColumnName("exemplo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("Vip")
                        .HasColumnType("boolean")
                        .HasColumnName("vip");

                    b.HasKey("Id")
                        .HasName("pk_clientes");

                    b.HasIndex("ClientePrincipalId")
                        .HasDatabaseName("ix_clientes_cliente_principal_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_clientes_tenant_id");

                    b.HasIndex("TenantId", "Nome")
                        .HasDatabaseName("ix_clientes_tenant_id_nome");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.Comunicacao.MensagemEnviada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgendamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("agendamento_id");

                    b.Property<string>("Assunto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assunto");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Corpo")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("corpo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("destino");

                    b.Property<string>("Erro")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("erro");

                    b.Property<string>("IdExterno")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("id_externo");

                    b.Property<Guid?>("OrdemServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ordem_servico_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id")
                        .HasName("pk_mensagens_enviadas");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_mensagens_enviadas_cliente_id");

                    b.HasIndex("OrdemServicoId")
                        .HasDatabaseName("ix_mensagens_enviadas_ordem_servico_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_mensagens_enviadas_tenant_id");

                    b.ToTable("mensagens_enviadas", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.Comunicacao.PreferenciaNotificacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id")
                        .HasName("pk_preferencias_notificacao");

                    b.HasIndex("TenantId", "TipoEvento", "Canal")
                        .IsUnique()
                        .HasDatabaseName("ix_preferencias_notificacao_tenant_id_tipo_evento_canal");

                    b.ToTable("preferencias_notificacao", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.Financeiro.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("desconto");

                    b.Property<DateTimeOffset?>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<string>("MotivoRecusa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_recusa");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ordem_servico_id");

                    b.Property<DateTimeOffset?>("RespondidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("respondido_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("ValorMaoDeObra")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_mao_de_obra");

                    b.Property<decimal>("ValorPecas")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_pecas");

                    b.HasKey("Id")
                        .HasName("pk_orcamentos");

                    b.HasIndex("OrdemServicoId")
                        .IsUnique()
                        .HasDatabaseName("ix_orcamentos_ordem_servico_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_orcamentos_tenant_id");

                    b.ToTable("orcamentos", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.Financeiro.OrcamentoEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("canal");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("orcamento_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id")
                        .HasName("pk_orcamento_eventos");

                    b.HasIndex("OrcamentoId")
                        .HasDatabaseName("ix_orcamento_eventos_orcamento_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_orcamento_eventos_tenant_id");

                    b.ToTable("orcamento_eventos", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.Financeiro.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Forma")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("forma");

                    b.Property<string>("Observacao")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("observacao");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ordem_servico_id");

                    b.Property<Guid?>("RegistradoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("registrado_por_usuario_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id")
                        .HasName("pk_pagamentos");

                    b.HasIndex("OrdemServicoId")
                        .HasDatabaseName("ix_pagamentos_ordem_servico_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_pagamentos_tenant_id");

                    b.ToTable("pagamentos", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.OrdensServico.OrdemServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AgendamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("agendamento_id");

                    b.Property<int?>("AparelhoId")
                        .HasColumnType("integer")
                        .HasColumnName("aparelho_id");

                    b.Property<string>("AparelhoMarca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aparelho_marca");

                    b.Property<string>("AparelhoModelo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("aparelho_modelo");

                    b.Property<string>("ChaveIdempotencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chave_idempotencia");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("CodigoAcompanhamento")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("codigo_acompanhamento");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DescricaoProblema")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("descricao_problema");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("etapa");

                    b.Property<DateTimeOffset?>("EtapaDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("etapa_desde");

                    b.Property<bool>("Exemplo")
                        .HasColumnType("boolean")
                        .HasColumnName("exemplo");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("observacoes");

                    b.Property<DateOnly?>("PrazoEstimado")
                        .HasColumnType("date")
                        .HasColumnName("prazo_estimado");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prioridade");

                    b.Property<Guid?>("ResponsavelTecnicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_tecnico_id");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("servico_id");

                    b.Property<string>("StatusAprovacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_aprovacao");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status_pagamento");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ordens_servico");

                    b.HasIndex("AgendamentoId")
                        .HasDatabaseName("ix_ordens_servico_agendamento_id");

                    b.HasIndex("AparelhoId")
                        .HasDatabaseName("ix_ordens_servico_aparelho_id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_ordens_servico_cliente_id");

                    b.HasIndex("CodigoAcompanhamento")
                        .IsUnique()
                        .HasDatabaseName("ix_ordens_servico_codigo_acompanhamento");

                    b.HasIndex("ResponsavelTecnicoId")
                        .HasDatabaseName("ix_ordens_servico_responsavel_tecnico_id");

                    b.HasIndex("ServicoId")
                        .HasDatabaseName("ix_ordens_servico_servico_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_ordens_servico_updated_at");

                    b.HasIndex("TenantId", "ChaveIdempotencia")
                        .IsUnique()
                        .HasDatabaseName("ix_ordens_servico_tenant_id_chave_idempotencia");

                    b.HasIndex("TenantId", "Etapa")
                        .HasDatabaseName("ix_ordens_servico_tenant_id_etapa");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_ordens_servico_tenant_id_numero");

                    b.ToTable("ordens_servico", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.OrdensServico.OrdemServicoComentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AutorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("autor_usuario_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ordem_servico_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("texto");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ordem_servico_comentarios");

                    b.HasIndex("OrdemServicoId")
                        .HasDatabaseName("ix_ordem_servico_comentarios_ordem_servico_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_ordem_servico_comentarios_updated_at");

                    b.ToTable("ordem_servico_comentarios", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.OrdensServico.OrdemServicoHistoricoEtapa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("DeEtapa")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("de_etapa");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ordem_servico_id");

                    b.Property<string>("ParaEtapa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("para_etapa");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_ordem_servico_historico_etapas");

                    b.HasIndex("OrdemServicoId")
                        .HasDatabaseName("ix_ordem_servico_historico_etapas_ordem_servico_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_ordem_servico_historico_etapas_updated_at");

                    b.ToTable("ordem_servico_historico_etapas", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.OrdensServico.OrdemServicoPeca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<decimal>("CustoUnitarioNoUso")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("custo_unitario_no_uso");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ordem_servico_id");

                    b.Property<int>("PecaId")
                        .HasColumnType("integer")
                        .HasColumnName("peca_id");

                    b.Property<decimal>("PrecoVendaNoUso")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_venda_no_uso");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ordem_servico_pecas");

                    b.HasIndex("OrdemServicoId")
                        .HasDatabaseName("ix_ordem_servico_pecas_ordem_servico_id");

                    b.HasIndex("PecaId")
                        .HasDatabaseName("ix_ordem_servico_pecas_peca_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_ordem_servico_pecas_updated_at");

                    b.ToTable("ordem_servico_pecas", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.OrdensServico.OrdemServicoReatribuicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("DeUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("de_usuario_id");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ordem_servico_id");

                    b.Property<Guid?>("ParaUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("para_usuario_id");

                    b.Property<Guid?>("PorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("por_usuario_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_ordem_servico_reatribuicoes");

                    b.HasIndex("OrdemServicoId")
                        .HasDatabaseName("ix_ordem_servico_reatribuicoes_ordem_servico_id");

                    b.ToTable("ordem_servico_reatribuicoes", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.Reputacao.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comentario");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("Nota")
                        .HasColumnType("integer")
                        .HasColumnName("nota");

                    b.Property<Guid>("OrdemServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ordem_servico_id");

                    b.Property<int>("Recomendacao")
                        .HasColumnType("integer")
                        .HasColumnName("recomendacao");

                    b.Property<string>("ResolucaoNota")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("resolucao_nota");

                    b.Property<bool>("Resolvida")
                        .HasColumnType("boolean")
                        .HasColumnName("resolvida");

                    b.Property<DateTimeOffset?>("ResolvidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolvida_em");

                    b.Property<Guid?>("ResolvidaPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolvida_por_usuario_id");

                    b.Property<Guid?>("ResponsavelTecnicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsavel_tecnico_id");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("servico_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_avaliacoes");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("ix_avaliacoes_cliente_id");

                    b.HasIndex("OrdemServicoId")
                        .IsUnique()
                        .HasDatabaseName("ix_avaliacoes_ordem_servico_id");

                    b.HasIndex("ServicoId")
                        .HasDatabaseName("ix_avaliacoes_servico_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_avaliacoes_tenant_id");

                    b.ToTable("avaliacoes", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.ServicosEPecas.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contato")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contato");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_fornecedores");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_fornecedores_tenant_id");

                    b.ToTable("fornecedores", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.ServicosEPecas.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<decimal?>("CustoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("custo_unitario");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo");

                    b.Property<Guid?>("OrdemServicoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ordem_servico_id");

                    b.Property<int>("PecaId")
                        .HasColumnType("integer")
                        .HasColumnName("peca_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("SaldoApos")
                        .HasColumnType("integer")
                        .HasColumnName("saldo_apos");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_movimentacoes_estoque");

                    b.HasIndex("PecaId")
                        .HasDatabaseName("ix_movimentacoes_estoque_peca_id");

                    b.ToTable("movimentacoes_estoque", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.ServicosEPecas.Peca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<decimal>("CustoUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("custo_unitario");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<int>("EstoqueMinimo")
                        .HasColumnType("integer")
                        .HasColumnName("estoque_minimo");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("integer")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<decimal>("PrecoVenda")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_venda");

                    b.Property<int>("QuantidadeEmEstoque")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_em_estoque");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_pecas");

                    b.HasIndex("FornecedorId")
                        .HasDatabaseName("ix_pecas_fornecedor_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_pecas_tenant_id");

                    b.ToTable("pecas", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.ServicosEPecas.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AgendavelOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("agendavel_online");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<int>("CapacidadeSimultanea")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade_simultanea");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("DuracaoEstimadaMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracao_estimada_minutos");

                    b.Property<bool>("Exemplo")
                        .HasColumnType("boolean")
                        .HasColumnName("exemplo");

                    b.Property<bool>("ExigeDiagnostico")
                        .HasColumnType("boolean")
                        .HasColumnName("exige_diagnostico");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int?>("PrazoMedioDias")
                        .HasColumnType("integer")
                        .HasColumnName("prazo_medio_dias");

                    b.Property<decimal>("PrecoBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("preco_base");

                    b.Property<int?>("SlaHoras")
                        .HasColumnType("integer")
                        .HasColumnName("sla_horas");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_servicos");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_servicos_tenant_id");

                    b.ToTable("servicos", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.ServicosEPecas.ServicoChecklistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("ServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("servico_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_servico_checklist_itens");

                    b.HasIndex("ServicoId")
                        .HasDatabaseName("ix_servico_checklist_itens_servico_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_servico_checklist_itens_tenant_id");

                    b.ToTable("servico_checklist_itens", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Modules.ServicosEPecas.ServicoPeca", b =>
                {
                    b.Property<int>("ServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("servico_id");

                    b.Property<int>("PecaId")
                        .HasColumnType("integer")
                        .HasColumnName("peca_id");

                    b.Property<int>("QuantidadePadrao")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_padrao");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("ServicoId", "PecaId")
                        .HasName("pk_servico_pecas");

                    b.HasIndex("PecaId")
                        .HasDatabaseName("ix_servico_pecas_peca_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_servico_pecas_tenant_id");

                    b.ToTable("servico_pecas", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Shared.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<Guid?>("SubstituidoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("substituido_por_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TipoCliente")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_cliente");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_tokens_usuario_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Shared.Auth.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_usuarios_tenant_id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("TechPro.Api.Shared.Tenancy.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<DateTimeOffset?>("OnboardingConcluidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("onboarding_concluido_em");

                    b.Property<string>("Politicas")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("politicas");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_slug");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_papel_claims_papeis_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("TechPro.Api.Shared.Auth.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_claims_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("TechPro.Api.Shared.Auth.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_logins_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_papeis_papeis_role_id");

                    b.HasOne("TechPro.Api.Shared.Auth.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_papeis_usuarios_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("TechPro.Api.Shared.Auth.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_tokens_usuarios_user_id");
                });

            modelBuilder.Entity("TechPro.Api.Modules.Agendamentos.Agendamento", b =>
                {
                    b.HasOne("TechPro.Api.Modules.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_agendamentos_clientes_cliente_id");

                    b.HasOne("TechPro.Api.Modules.ServicosEPecas.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agendamentos_servicos_servico_id");

                    b.Navigation("Cliente");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("TechPro.Api.Modules.Agendamentos.EntradaFilaEspera", b =>
                {
                    b.HasOne("TechPro.Api.Modules.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_fila_espera_clientes_cliente_id");

                    b.HasOne("TechPro.Api.Modules.ServicosEPecas.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fila_espera_servicos_servico_id");

                    b.Navigation("Cliente");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("TechPro.Api.Modules.Clientes.Aparelho", b =>
                {
                    b.HasOne("TechPro.Api.Modules.Clientes.Cliente", null)
                        .WithMany("Aparelhos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aparelhos_clientes_cliente_id");
                });

            modelBuilder.Entity("TechPro.Api.Modules.Clientes.Cliente", b =>
                {
                    b.HasOne("TechPro.Api.Modules.Clientes.Cliente", "ClientePrincipal")
                        .WithMany()
                        .HasForeignKey("ClientePrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_clientes_clientes_cliente_principal_id");

                    b.Navigation("ClientePrincipal");
                });

            modelBuilder.Entity("TechPro.Api.Modules.Financeiro.Orcamento", b =>
                {
                    b.HasOne("TechPro.Api.Modules.OrdensServico.OrdemServico", null)
                        .WithMany()
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orcamentos_ordens_servico_ordem_servico_id");
                });

            modelBuilder.Entity("TechPro.Api.Modules.Financeiro.OrcamentoEvento", b =>
                {
                    b.HasOne("TechPro.Api.Modules.Financeiro.Orcamento", null)
                        .WithMany("Eventos")
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orcamento_eventos_orcamentos_orcamento_id");
                });

            modelBuilder.Entity("TechPro.Api.Modules.Financeiro.Pagamento", b =>
                {
                    b.HasOne("TechPro.Api.Modules.OrdensServico.OrdemServico", null)
                        .WithMany()
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagamentos_ordens_servico_ordem_servico_id");
                });

            modelBuilder.Entity("TechPro.Api.Modules.OrdensServico.OrdemServico", b =>
                {
                    b.HasOne("TechPro.Api.Modules.Agendamentos.Agendamento", "Agendamento")
                        .WithMany()
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ordens_servico_agendamentos_agendamento_id");

                    b.HasOne("TechPro.Api.Modules.Clientes.Aparelho", "Aparelho")
                        .WithMany()
                        .HasForeignKey("AparelhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ordens_servico_aparelhos_aparelho_id");

                    b.HasOne("TechPro.Api.Modules.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ordens_servico_clientes_cliente_id");

                    b.HasOne("TechPro.Api.Shared.Auth.Usuario", "ResponsavelTecnico")
                        .WithMany()
                        .HasForeignKey("ResponsavelTecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ordens_servico_users_responsavel_tecnico_id");

                    b.HasOne("TechPro.Api.Modules.ServicosEPecas.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ordens_servico_servicos_servico_id");

                    b.Navigation("Agendamento");

                    b.Navigation("Aparelho");

                    b.Navigation("Cliente");

                    b.Navigation("ResponsavelTecnico");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("TechPro.Api.Modules.OrdensServico.OrdemServicoComentario", b =>
                {
                    b.HasOne("TechPro.Api.Modules.OrdensServico.OrdemServico", null)
                        .WithMany()
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ordem_servico_comentarios_ordens_servico_ordem_servico_id");
                });

            modelBuilder.Entity("TechPro.Api.Modules.OrdensServico.OrdemServicoHistoricoEtapa", b =>
                {
                    b.HasOne("TechPro.Api.Modules.OrdensServico.OrdemServico", null)
                        .WithMany("Historico")
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ordem_servico_historico_etapas_ordens_servico_ordem_servico");
                });

            modelBuilder.Entity("TechPro.Api.Modules.OrdensServico.OrdemServicoPeca", b =>
                {
                    b.HasOne("TechPro.Api.Modules.OrdensServico.OrdemServico", null)
                        .WithMany()
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ordem_servico_pecas_ordens_servico_ordem_servico_id");

                    b.HasOne("TechPro.Api.Modules.ServicosEPecas.Peca", "Peca")
                        .WithMany()
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ordem_servico_pecas_pecas_peca_id");

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("TechPro.Api.Modules.OrdensServico.OrdemServicoReatribuicao", b =>
                {
                    b.HasOne("TechPro.Api.Modules.OrdensServico.OrdemServico", null)
                        .WithMany()
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ordem_servico_reatribuicoes_ordens_servico_ordem_servico_id");
                });

            modelBuilder.Entity("TechPro.Api.Modules.Reputacao.Avaliacao", b =>
                {
                    b.HasOne("TechPro.Api.Modules.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_avaliacoes_clientes_cliente_id");

                    b.HasOne("TechPro.Api.Modules.OrdensServico.OrdemServico", "OrdemServico")
                        .WithMany()
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avaliacoes_ordens_servico_ordem_servico_id");

                    b.HasOne("TechPro.Api.Modules.ServicosEPecas.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avaliacoes_servicos_servico_id");

                    b.Navigation("Cliente");

                    b.Navigation("OrdemServico");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("TechPro.Api.Modules.ServicosEPecas.MovimentacaoEstoque", b =>
                {
                    b.HasOne("TechPro.Api.Modules.ServicosEPecas.Peca", "Peca")
                        .WithMany()
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_movimentacoes_estoque_pecas_peca_id");

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("TechPro.Api.Modules.ServicosEPecas.Peca", b =>
                {
                    b.HasOne("TechPro.Api.Modules.ServicosEPecas.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_pecas_fornecedores_fornecedor_id");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("TechPro.Api.Modules.ServicosEPecas.ServicoChecklistItem", b =>
                {
                    b.HasOne("TechPro.Api.Modules.ServicosEPecas.Servico", null)
                        .WithMany("Checklist")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_servico_checklist_itens_servicos_servico_id");
                });

            modelBuilder.Entity("TechPro.Api.Modules.ServicosEPecas.ServicoPeca", b =>
                {
                    b.HasOne("TechPro.Api.Modules.ServicosEPecas.Peca", "Peca")
                        .WithMany()
                        .HasForeignKey("PecaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_servico_pecas_pecas_peca_id");

                    b.HasOne("TechPro.Api.Modules.ServicosEPecas.Servico", null)
                        .WithMany("Pecas")
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_servico_pecas_servicos_servico_id");

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("TechPro.Api.Shared.Auth.RefreshToken", b =>
                {
                    b.HasOne("TechPro.Api.Shared.Auth.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TechPro.Api.Modules.Clientes.Cliente", b =>
                {
                    b.Navigation("Aparelhos");
                });

            modelBuilder.Entity("TechPro.Api.Modules.Financeiro.Orcamento", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("TechPro.Api.Modules.OrdensServico.OrdemServico", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("TechPro.Api.Modules.ServicosEPecas.Servico", b =>
                {
                    b.Navigation("Checklist");

                    b.Navigation("Pecas");
                });
#pragma warning restore 612, 618
        }
    }
}
